### ISSUE TITLE
When the kubelet volume stats metrics will be supported?

### ISSUE THREAD

**Issue by ejianlv** [Nexenta/nexentastor-csi-driver#9]
Hi,
It seems that below metrics are not supported yet, how about the plan to support them?

kubelet_volume_stats_capacity_bytes
kubelet_volume_stats_available_bytes
kubelet_volume_stats_used_bytes
kubelet_volume_stats_inodes
kubelet_volume_stats_inodes_free
kubelet_volume_stats_inodes_used

BRs/Jian

**Comment by Qeas** [comment]
Hi,
Correct me if I am wrong, but AFAIK those metrics are not provided by the CSI driver.

**Comment by Qeas** [comment]
not an issue
